---
- name: Gebe den Pfad der Vault-Datei aus
  debug:
    msg: "Der Pfad zur Vault-Datei ist: {{ vault_file }}"

- name: Prüfe, ob die Vault-Datei existiert
  stat:
    path: "{{ vault_file }}"
  register: vault_file_stat

- name: Eingabeaufforderung für Passwort zur Erstellung oder Entschlüsselung der Vault-Datei
  block:
    - name: Passwort erfassen (geheim)
      ansible.builtin.pause:
        prompt: "Bitte geben Sie das Passwort ein: "
        echo: no
      register: vault_password

    - name: Vault-Datei erstellen und verschlüsseln, falls sie nicht existiert
      when: not vault_file_stat.stat.exists
      shell: |
        echo '{{ vault_password.user_input }}' > /tmp/vault_pass.txt
        echo 'secret_key: "example_value"' | ansible-vault encrypt --vault-password-file=/tmp/vault_pass.txt --output {{ vault_file }} /dev/stdin
      args:
        executable: /bin/bash

    - name: Vault-Datei entschlüsseln und bearbeiten, falls sie existiert
      when: vault_file_stat.stat.exists
      shell: echo '{{ vault_password.user_input }}' | ansible-vault edit --vault-password-file=/dev/stdin {{ vault_file }}
      args:
        executable: /bin/bash

    - name: Lösche die temporäre Passwortdatei
      file:
        path: /tmp/vault_pass.txt
        state: absent
      when: not vault_file_stat.stat.exists
