---
- name: Prüfe, ob die Vault-Datei existiert
  stat:
    path: "{{ vault_file }}"
  register: vault_file_stat

- name: Eingabeaufforderung für Passwort zur Erstellung der Vault-Datei, falls sie nicht existiert
  when: not vault_file_stat.stat.exists
  vars:
    ansible_become_pass: "{{ vault_password }}"
  block:
    - name: Prompt für Passwort
      ansible.builtin.debug:
        msg: "Bitte geben Sie das Passwort zur Erstellung der Vault-Datei ein:"

    - name: Passwort erfassen (geheim)
      ansible.builtin.pause:
        prompt: "Passwort: "
        echo: no
      register: vault_password

    - name: Vault-Datei erstellen
      ansible.builtin.command:
        cmd: "ansible-vault create --vault-password-file=<(echo {{ vault_password.user_input }}) {{ vault_file }}"

- name: Eingabeaufforderung für Passwort zur Entschlüsselung, falls die Datei existiert
  when: vault_file_stat.stat.exists
  block:
    - name: Prompt für Passwort zur Entschlüsselung
      ansible.builtin.debug:
        msg: "Bitte geben Sie das Passwort zum Öffnen der Vault-Datei ein:"

    - name: Passwort erfassen (geheim)
      ansible.builtin.pause:
        prompt: "Passwort: "
        echo: no
      register: vault_password

    - name: Vault-Datei entschlüsseln und bearbeiten
      ansible.builtin.command:
        cmd: "ansible-vault edit --vault-password-file=<(echo {{ vault_password.user_input }}) {{ vault_file }}"
