---
- name: Gebe den Pfad der Vault-Datei aus
  debug:
    msg: "Der Pfad zur Vault-Datei ist: {{ vault_file }}"

- name: Prüfe, ob die Vault-Datei existiert
  stat:
    path: "{{ vault_file }}"
  register: vault_file_stat

- name: Vault-Datei erstellen und verschlüsseln, falls sie nicht existiert
  when: not vault_file_stat.stat.exists
  block:
    - name: Schreibe den initialen Inhalt in eine temporäre Datei
      copy:
        content: |
          # Initialer Inhalt, falls benötigt
          secret_key: "example_value"
        dest: /tmp/temp_vault_content.yml

    - name: Vault-Datei verschlüsseln und erstellen
      shell: |
        echo '{{ vault_secret }}' > /tmp/vault_pass.txt
        ansible-vault encrypt /tmp/temp_vault_content.yml --vault-password-file=/tmp/vault_pass.txt --output {{ vault_file }}
        rm -f /tmp/vault_pass.txt
      args:
        executable: /bin/bash

    - name: Lösche die temporäre Datei nach der Verschlüsselung
      file:
        path: /tmp/temp_vault_content.yml
        state: absent

- name: Vault-Datei entschlüsseln und bearbeiten, falls sie existiert
  when: vault_file_stat.stat.exists
  shell: |
    echo '{{ vault_secret }}' > /tmp/vault_pass.txt
    ansible-vault edit --vault-password-file=/tmp/vault_pass.txt {{ vault_file }}
    rm -f /tmp/vault_pass.txt
  args:
    executable: /bin/bash